version: '3.8'
services:
  nest-api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: nest-api 
    restart: always
    ports:
      - 8000:8000
    env_file:
      - .env

volumes:
  postgres:
    name: nest-prisma-docker